# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a base Python image
FROM python:3.10-slim AS base

# Set the working directory in the container
WORKDIR /app

# Copy the project file
COPY pyproject.toml README.md src /app/

# Install dependencies and the package
RUN pip install hatchling && \
    hatchling build && \
    pip install dist/*.whl

# Set the entry point to run the server
ENTRYPOINT ["mcp-dbutils", "--config", "/app/config.yaml"]
